# Default type of service is ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: php-backend-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: php-backend