# TODO: Setup Liveness probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-backend-deployment
spec:
  selector:
    matchLabels:
      app: php-backend                                    
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: php-backend
    spec:
      containers:
        - image: yashkapila/docker-php-app
          name: php-backend