# TODO: Setup Liveness probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  selector:
    matchLabels:
      app: react-frontend                                    
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - image: yashkapila/docker-react-app
          name: react-frontend
          ports:
            - containerPort: 80